name: 'firmable_taxi'
version: '1.0.0'

profile: 'firmable_taxi'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  firmable_taxi:
    staging:
      +materialized: view
      +schema: STAGING
      +tags: ["staging"]

    intermediate:
      +materialized: table
      +schema: INTERMEDIATE
      +tags: ["intermediate"]

    marts:
      +materialized: table
      +schema: MARTS
      +tags: ["marts"]