version: 2

models:
  - name: stg_yellow_taxi_trips

    tests:
      - valid_trip_duration:
          arguments:
            pickup_column: tpep_pickup_datetime
            dropoff_column: tpep_dropoff_datetime
          config:
            severity: warn

    columns:
      - name: vendor_id
        tests:
          - not_null

      - name: tpep_pickup_datetime
        tests:
          - not_null

      - name: tpep_dropoff_datetime
        tests:
          - not_null

      - name: pu_location_id
        tests:
          - not_null

      - name: do_location_id
        tests:
          - not_null

  - name: stg_taxi_zone_lookup
    columns:
      - name: location_id
        tests:
          - unique
          - not_null